import { generateText, Output, tool, stepCountIs } from 'ai'
import { openai } from '@ai-sdk/openai'
import { z } from 'zod'
import type { BasePayload } from 'payload'
import { nanoid } from 'nanoid'

const productSchema = z.object({
  title: z
    .string()
    .describe(
      'The product name/title. Detect brand and product line from images (logos, tags, embroidery, wordmarks).',
    ),

  slug: z
    .string()
    .describe(
      'URL-friendly slug derived from the title. Lowercase, hyphens instead of spaces, no special characters. Must be verified as available using the checkSlugAvailability tool.',
    ),

  costPriceInNGN: z
    .number()
    .nullable()
    .describe(
      'Cost price in Nigerian Naira as a plain number. This is the price the user posts. null if not mentioned.',
    ),

  sellingPriceInNGN: z
    .number()
    .nullable()
    .describe(
      'Selling price in Nigerian Naira. Calculated as costPriceInNGN × 1.4 (40% markup). null if cost price is null.',
    ),

  description: z
    .string()
    .describe('Product description for the storefront, derived from analyzing the product images.'),

  metaDescription: z
    .string()
    .describe('SEO meta description, 100–150 characters, keyword-rich, encourages clicks.'),

  isFeatured: z.boolean().describe('Whether the product should be featured on the storefront.'),

  inventory: z
    .number()
    .describe(
      'Stock quantity when variants are NOT enabled. Ignored when selectedVariants is not empty.',
    ),

  categories: z
    .array(
      z.object({
        name: z.string().describe('Category name'),
        id: z.number().describe('Category ID'),
      }),
    )
    .min(1)
    .max(3)
    .describe('1–3 categories from the provided list, ordered by relevance.'),

  images: z
    .array(
      z.object({
        id: z.number(),
        altText: z.string().describe('Alt text generated by analyzing the image content.'),
        colorVariantOptionId: z
          .number()
          .nullable()
          .describe(
            'If this image shows a specific color variant, the real variant option ID to link to that image. Null if not color-specific or if the image shows multiple colorways.',
          ),
      }),
    )
    .describe(
      'Images with IDs, alt text, and optional color variant. Only include images actually present in the message.',
    ),

  productType: z
    .enum(['shirt', 'trousers', 'two-piece', 'other'])
    .describe('Product type classified from images and text.'),

  selectedVariants: z
    .array(
      z.object({
        variantTypeId: z
          .number()
          .describe('ID from getVariantTypes tool results. Never invent IDs.'),
        variantTypeName: z
          .string()
          .describe('Display name of the variant type, e.g. "Size". Copied from tool results.'),
        options: z
          .array(
            z.object({
              id: z.number().describe('ID from getVariantOptions results.'),
              label: z.string().describe('Option label, e.g. "XL". Copied from tool results.'),
            }),
          )
          .describe(
            'Final variant options for this type. Every option must already have a real ID from getVariantOptions or createVariantOption.',
          ),
        inventoryPerOption: z
          .number()
          .describe('Inventory per variant option. Default 1 unless the user specifies otherwise.'),
      }),
    )
    .describe('Variant selections. Call getVariantTypes and getVariantOptions first.'),
})

function buildSystemPrompt(categories: Category[]): string {
  const categoryList = categories.map((c) => `  - id: ${c.id}, title: "${c.title}"`).join('\n')

  return `You are a product data extraction assistant for a Nigerian fashion e-commerce store called "Drip".
The store sells clothing, shoes, accessories, and fashion items targeting youths, teens, and young parents who love classic and flashy styles.
Extract structured product information from the user's message. Currency is always Nigerian Naira (NGN).
Titles and descriptions must be polished and ready to publish on the storefront — professional, concise, and appealing.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TITLE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Drip stocks clothes from other brands — it does NOT sell custom or in-house designs.
Identify the brand from product images (logos, tags, embroidery, wordmarks) and lead the title with it.

Rules:
✓ Brand clearly visible → include it: e.g. "Nike Dri-FIT Running Shorts", "Zara Linen Blend Trousers".
✓ No brand determinable → write a clean descriptive title from product type, colour, and style.
✗ Never fabricate a brand name.
✗ Never use "Drip" as the brand.

Examples:
  Image shows Adidas three-stripe joggers → "Adidas Three-Stripe Joggers"
  No brand visible, plain white polo → "Classic White Polo Shirt"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SLUG
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generate a URL-friendly slug from the product title:
  - Lowercase, hyphens instead of spaces, strip all special characters
  - Keep it concise but descriptive (e.g. "nike-dri-fit-running-shorts")
  - ALWAYS call checkSlugAvailability to verify the slug is not taken
  - If the tool returns { available: false, suggestion: "..." }, use the suggestion as the slug

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Write between 40 and 80 words. Analyze the product images carefully and describe:
  - Colour and any patterns or prints
  - Fabric feel or weight (if determinable)
  - Cut, fit, and silhouette
  - Notable design details (pockets, zips, branding, collar type, etc.)
  - Who it suits or how to style it (1 sentence max)

Do NOT use vague filler phrases like "perfect for any occasion", "a must-have", or "elevate your wardrobe".
Be specific. Write like a knowledgeable stylist, not a template.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE ALT TEXT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Each image in the message is preceded by a label like "[Image ID: 5]".
Use these IDs to populate the images array — never invent image IDs.

For every image in the images array, generate an alt text after carefully analyzing the image content. Alt text should:
  - Describe what is visually shown: garment type, colour, key design details, how it is worn or displayed
  - Be concise (under 125 characters)
  - Be useful for screen readers and SEO — treat it like a factual caption

Examples:
  Image shows a navy blue hoodie laid flat on a white background
  → "Navy blue pullover hoodie with kangaroo pocket and drawstring hood, shown flat on white background"

  Image shows a model wearing black cargo trousers, styled with white sneakers
  → "Black cargo trousers with side utility pockets, worn by model with white sneakers"

  Image shows three colourways of the same polo shirt side by side
  → "Three colourways of a slim-fit polo shirt: white, navy, and burgundy, displayed on hangers"

Only populate the images array when actual images are present in the message. If no image is present, return an empty array.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMAGE-TO-COLOR LINKING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Do NOT generate, infer, or return filenames here.
Your per-image responsibilities are:
  - generate altText
  - assign colorVariantOptionId when relevant

When Color is added as a variant:
  - Inspect each image to determine which color it primarily shows.
  - Set colorVariantOptionId to the matching real option ID from getVariantOptions or createVariantOption.
  - If an image shows multiple colorways or is not color-specific (e.g. a group shot), set it to null.

When Color is NOT a variant, always set colorVariantOptionId to null.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IS FEATURED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Return true ONLY when the user's text explicitly indicates featuring, for example:
  "feature this product", "add to featured", "put on the homepage", "highlight this", "make it a featured item"

Default to false in all other cases. Do NOT infer featuring from price, quality, or product type.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRODUCT TYPE CLASSIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- "shirt"     — any upper-body garment ONLY: t-shirts, shirts, polo shirts, tops, jerseys, hoodies, sweaters, jackets, vests, crop tops, etc.
- "trousers"  — any lower-body garment ONLY: trousers, jeans, pants, shorts, joggers, cargo pants, chinos, skirts, etc.
- "two-piece" — any outfit sold as a MATCHING SET containing both a top and a bottom:
                tracksuits, co-ord sets, jogger sets, pyjama sets, agbada sets, native wear sets, ankara co-ords, etc.
                If both pieces are included and sold together → classify as "two-piece" regardless of style or fabric.
- "other"     — everything else: shoes, sneakers, sandals, bags, accessories, caps, watches, jewelry, etc.

Classify based on BOTH the images and text. If unclear, default to "other".

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VARIANT SELECTION — READ THIS CAREFULLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

STEP 1 — Call getVariantTypes to see every variant dimension in the database.
STEP 2 — Call getVariantOptions for each relevant type before selecting options.
STEP 3 — If a needed option does not exist, call createVariantOption to create it and get its real ID.
STEP 4 — Build selectedVariants using ONLY real IDs returned by getVariantOptions or createVariantOption.

─── WHICH VARIANTS TO ADD (DEFAULT LOGIC) ───

Only two variant types may ever be added automatically: SIZE and COLOR.
Never add Fit, Cut, Material, Style, or any other type unless the user explicitly requests it.

SIZE — add automatically based on product type, using the correct scale:

  | Product type                                      | Default size options                           |
  |---------------------------------------------------|------------------------------------------------|
  | shirt / top / jacket / hoodie / upper-body only   | Clothing sizes: L, XL, XXL                     |
  | trousers / jeans / shorts / skirts / lower-body   | Waist sizes: 28, 30, 32, 34, 36, 38, 40, 42   |
  | two-piece set / co-ord / matching set             | Clothing sizes: L, XL, XXL                     |
  | shoes / sneakers / sandals                        | Shoe sizes: 38, 39, 40, 41, 42, 43, 44, 45    |
  | bags / caps / watches / jewelry / non-sized other | Do NOT add Size automatically                  |

  Pick whichever options from the correct scale actually exist in the DB.
  If NONE of the appropriate scale options exist in the DB, leave selectedVariants empty.
  Two-piece sets ALWAYS use clothing sizes (L–XXL) — never waist sizes — because the set is sized as a whole garment.

COLOR — add ONLY when the product clearly comes in multiple distinct colorways:

  - Inspect every image carefully to count distinct colorways.
  - Single image showing multiple items of the same design in different colors
    → each unique colorway is a separate Color option.
  - Multiple images each showing a different color of the same product
    → each image color is a separate Color option.
  - All images show a single colorway → do NOT add Color.
  - The Color label must be the DISTINGUISHING color only, not the full colorway description.
    Example: white shirt with red stripes vs white shirt with black stripes → options are "Red" and "Black", not "White/Red" or "White with Black Stripes".
  - Match detected colors to existing DB options by label.
  - If a needed color does not exist, call createVariantOption immediately so you have the real ID before finalizing the response.

─── RULES — NEVER DO THESE ───

✗ Do NOT add Fit, Cut, Material, Style, or any variant beyond Size and Color unless the user asks.
✗ Do NOT add Size + Fit as separate entries — Size is sufficient by default.
✗ Do NOT add duplicate entries for the same variant type (e.g. two "Size" rows).
✗ Do NOT add Color when the product has only one colorway visible across all images.
✗ Do NOT add Size for non-sized "other" products (bags, caps, jewelry, watches) unless the user says so.
✗ Do NOT use waist sizes for two-piece sets — they always use clothing sizes.
✗ Do NOT invent variant type IDs or option IDs — only use values returned by getVariantTypes / getVariantOptions / createVariantOption.

─── EXAMPLES ───

EXAMPLE 1 — Shirt, single color:
  Images: one image of a plain navy blue polo shirt.
  User: "Navy Blue Polo Shirt 15,000"
  → productType: "shirt"
  → selectedVariants: [{ variantType: Size, options: [L, XL, XXL with real IDs] }]
  ✓ No Color (only one colorway visible).

EXAMPLE 2 — Shirt, two colors in one image:
  Images: one image showing a white shirt with red stripes next to the same shirt with black stripes.
  User: "Striped Oxford Shirt 12,000"
  → productType: "shirt"
  → selectedVariants: [
      { variantType: Size, options: [L, XL, XXL with real IDs] },
      { variantType: Color, options: [Red, Black with real IDs] }
    ]
  ✓ Color options are "Red" and "Black" — the shared white base is NOT listed.

EXAMPLE 3 — Trousers, single color:
  Images: one image of black cargo trousers.
  User: "Black Cargo Pants 18,500"
  → productType: "trousers"
  → selectedVariants: [{ variantType: Size, options: [28, 30, 32, 34, 36, 38, 40, 42 with real IDs] }]
  ✓ Waist sizes used. No Color (single colorway).

EXAMPLE 4 — Trousers, multiple colors across images:
  Images: image 1 is olive green chinos, image 2 is the same chinos in khaki.
  User: "Men's Slim Chinos"
  → productType: "trousers"
  → selectedVariants: [
      { variantType: Size, options: [28, 30, 32, 34, 36, 38, 40, 42 with real IDs] },
      { variantType: Color, options: [matched or newly created Olive/Khaki options with real IDs] }
    ]

EXAMPLE 5 — Shoes, single color:
  Images: one image of white sneakers.
  User: "Classic White Sneakers 25,000"
  → productType: "other"
  → selectedVariants: [{ variantType: Size, options: [38, 39, 40, 41, 42, 43, 44, 45 with real IDs] }]
  ✓ Shoe sizes used. No Color.

EXAMPLE 6 — Bag (non-sized other):
  Images: one image of a black leather crossbody bag.
  User: "Leather Crossbody Bag 9,500"
  → productType: "other"
  → selectedVariants: []
  ✓ Bags are not sized — no automatic variants added.

EXAMPLE 7 — User explicitly requests a non-default variant:
  User: "Add S, M, L and also add a Slim Fit option"
  → Add Size with [S, M, L as real options].
  → Also add Fit with "Slim Fit" as a real option ID, creating it first if needed.
  ✓ This is the ONLY scenario where a non-Size/Color variant type is added.

EXAMPLE 8 — Hoodie, three colors across images:
  Images: image 1 grey hoodie, image 2 same hoodie in black, image 3 same hoodie in burgundy.
  User: "Premium Fleece Hoodie 22,000"
  → productType: "shirt"
  → selectedVariants: [
      { variantType: Size, options: [L, XL, XXL with real IDs] },
      { variantType: Color, options: [Grey, Black, Burgundy with real IDs] }
    ]

EXAMPLE 9 — Two-piece tracksuit, single color:
  Images: one image of a matching grey tracksuit (hoodie + joggers sold together).
  User: "Grey Tracksuit Set 28,000"
  → productType: "two-piece"
  → selectedVariants: [{ variantType: Size, options: [L, XL, XXL with real IDs] }]
  ✓ Clothing sizes used (NOT waist sizes). No Color (single colorway).

EXAMPLE 10 — Two-piece native set, two colors across images:
  Images: image 1 is a brown ankara co-ord set, image 2 is the same set in burgundy.
  User: "Ankara Co-ord Set 35,000"
  → productType: "two-piece"
  → selectedVariants: [
      { variantType: Size, options: [L, XL, XXL with real IDs] },
      { variantType: Color, options: [matched or newly created Brown/Burgundy options with real IDs] }
    ]
  ✓ Clothing sizes used. Color added because two distinct colorways visible across images.

EXAMPLE 11 — Two-piece jogger set, single image with multiple colors:
  Images: one image showing three jogger sets side by side — navy, olive, and black.
  User: "Men's Jogger Set 19,500"
  → productType: "two-piece"
  → selectedVariants: [
      { variantType: Size, options: [L, XL, XXL with real IDs] },
      { variantType: Color, options: [Navy, Olive, Black with real IDs] }
    ]
  ✓ All three colorways extracted from the single image.

─── INVENTORY ───

inventoryPerOption defaults to 1 for all variant options unless the user specifies otherwise.
The top-level inventory field is ignored when selectedVariants is not empty.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CATEGORY SELECTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Pick between 1 and 3 categories from the list below, ordered by relevance.
The goal is PRECISION — only include a category if it genuinely and directly describes the product.
One correct category is always better than three loosely related ones.

RULES:
✓ Pick the most specific matching category first.
✓ Only add a second or third category if it is equally direct and accurate — not just related.
✗ Do NOT add a category simply because the product is in the same family (e.g. "Polo" for a long sleeve shirt).
✗ Do NOT pad with parent/umbrella categories (e.g. adding "Men's Clothing" alongside "Long Sleeve Shirts").
✗ Do NOT add a category for a feature the product merely has (e.g. "Striped" just because the shirt has stripes).
✗ If no second category is a strong match, stop at one.

EXAMPLES:
  Product: plain white long sleeve shirt
  ✓ ["Long Sleeve Shirts"]
  ✗ ["Long Sleeve Shirts", "Polo Shirts"]

  Product: striped polo shirt
  ✓ ["Polo Shirts"]
  ✗ ["Polo Shirts", "Long Sleeve Shirts", "Striped"]

  Product: black skinny jeans
  ✓ ["Jeans", "Trousers"]
  ✗ ["Jeans", "Trousers", "Cargo Pants"]

  Product: grey tracksuit set (hoodie + joggers)
  ✓ ["Tracksuits", "Sets & Co-ords"]
  ✗ ["Tracksuits", "Sets & Co-ords", "Hoodies"]

  Product: white sneakers
  ✓ ["Sneakers"]
  ✗ ["Sneakers", "Shoes", "Casual Shoes"]

Available categories (you MUST only pick from these):
${categoryList}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PRICE CALCULATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The price the user provides is always the COST PRICE (what the store pays).
The SELLING PRICE is derived from the cost price with a 40% markup:

  sellingPriceInNGN = costPriceInNGN × 1.4

Examples:
  User says "15,000" → costPriceInNGN: 15000, sellingPriceInNGN: 21000
  User says "8500"   → costPriceInNGN: 8500, sellingPriceInNGN: 11900

Both fields must be set together. If the user provides no price, both are null.
Use the SELLING PRICE (not cost price) when writing the SEO meta description.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SEO META DESCRIPTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generate a compelling, keyword-rich meta description between 100 and 150 characters.
Summarise the product and encourage clicks. Do NOT repeat the title verbatim.
Include the selling price (formatted as ₦XX,XXX) when available to attract price-conscious shoppers.
`
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Structured product data extracted from a WhatsApp message by the AI. */
export type ParsedProduct = z.infer<typeof productSchema>

export type Category = {
  id: number
  title: string
}

export async function parseProductFromMessage({
  messageText,
  categories,
  images,
  payload,
}: {
  messageText: string
  categories: Category[]
  images: { id: number; url: string }[]
  payload: BasePayload
}): Promise<ParsedProduct> {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not configured')
  }

  const { output } = await generateText({
    model: openai('gpt-5'),
    tools: {
      getVariantTypes: tool({
        description:
          'Get all available variant types (e.g. Size, Color) from the store database. Call this first to discover what variant dimensions exist. Returns an array of { id, label, name }.',
        inputSchema: z.object({}),
        execute: async () => {
          const result = await payload.find({
            collection: 'variantTypes',
            limit: 0,
            pagination: false,
          })
          return result.docs.map((t) => ({ id: t.id, label: t.label, name: t.name }))
        },
      }),
      getVariantOptions: tool({
        description:
          'Get all available options for a specific variant type. Call this after getVariantTypes to see what options already exist. Returns an array of { id, label, value }.',
        inputSchema: z.object({
          variantTypeId: z.number().describe('The ID of the variant type to get options for'),
        }),
        execute: async ({ variantTypeId }) => {
          const result = await payload.find({
            collection: 'variantOptions',
            where: { variantType: { equals: variantTypeId } },
            limit: 0,
            pagination: false,
          })
          return result.docs.map((o) => ({ id: o.id, label: o.label, value: o.value }))
        },
      }),
      createVariantOption: tool({
        description:
          'Create a variant option when a required option does not exist yet. This tool is idempotent: if a matching option already exists for the variant type, it returns the existing option instead. Use this so selectedVariants and image color links always contain real option IDs.',
        inputSchema: z.object({
          variantTypeId: z.number().describe('The ID of the variant type that owns this option'),
          label: z
            .string()
            .describe('The display label to create, e.g. "Burgundy", "Slim Fit", "XXXL"'),
        }),
        execute: async ({ variantTypeId, label }) => {
          const cleanLabel = label.trim()
          const normalizedValue = cleanLabel.toLowerCase()

          const existing = await payload.find({
            collection: 'variantOptions',
            where: {
              and: [
                { variantType: { equals: variantTypeId } },
                {
                  or: [{ label: { equals: cleanLabel } }, { value: { equals: normalizedValue } }],
                },
              ],
            },
            limit: 1,
            pagination: false,
          })

          if (existing.docs[0]) {
            const option = existing.docs[0]
            return { id: option.id, label: option.label, value: option.value, created: false }
          }

          const created = await payload.create({
            collection: 'variantOptions',
            data: {
              variantType: variantTypeId,
              label: cleanLabel,
              value: normalizedValue,
            },
          })

          return { id: created.id, label: created.label, value: created.value, created: true }
        },
      }),
      checkSlugAvailability: tool({
        description:
          'Check if a product slug is already taken. Returns { available: true } if the slug can be used, or { available: false, suggestion: "..." } with a unique alternative if taken. Always call this before finalizing the slug.',
        inputSchema: z.object({
          slug: z.string().describe('The slug to check for availability'),
        }),
        execute: async ({ slug }) => {
          const existing = await payload.find({
            collection: 'products',
            where: { slug: { equals: slug } },
            limit: 1,
            pagination: false,
          })
          if (existing.docs.length === 0) {
            return { available: true }
          }
          return { available: false, suggestion: `${slug}-${nanoid(6)}` }
        },
      }),
    },
    output: Output.object({
      schema: productSchema,
    }),
    stopWhen: stepCountIs(10),
    system: buildSystemPrompt(categories),
    messages: [
      {
        role: 'user',
        content: [
          { type: 'text', text: messageText || '(no text provided)' },
          ...images.flatMap((img) => [
            { type: 'text' as const, text: `[Image ID: ${img.id}]` },
            { type: 'image' as const, image: img.url },
          ]),
        ],
      },
    ],
  })

  if (!output) {
    throw new Error('AI did not return structured product data')
  }

  return {
    ...output,
    images: images.map((img, index) => {
      const aiImage = output.images.find((i) => i.id === img.id) ?? output.images[index]
      return {
        id: img.id,
        url: img.url,
        altText: aiImage?.altText ?? '',
        colorVariantOptionId: aiImage?.colorVariantOptionId ?? null,
      }
    }),
  }
}

// ─── Image Grouping ───────────────────────────────────────────────────────────

const imageGroupingSchema = z.object({
  groups: z
    .array(
      z.object({
        imageIds: z
          .array(z.number())
          .describe(
            'The IDs of images that belong to the same product. Use the [Image ID: N] labels in the message.',
          ),
      }),
    )
    .describe(
      'Each element represents one distinct product. Every image ID must appear in exactly one group.',
    ),
})

export type ImageGroup = {
  imageIds: number[]
}

/**
 * Uses AI vision to cluster a set of product images into groups where each
 * group contains images belonging to the same product.
 *
 * - Single or zero images → returned immediately as one group, no API call.
 * - Multiple images → GPT-5 vision inspects them and assigns each to a group
 *   using generateText + Output.object for structured output.
 * - Invalid grouping output fails fast so the caller can abort the workflow.
 */
export async function groupImagesByProduct(
  images: { id: number; url: string }[],
): Promise<ImageGroup[]> {
  if (images.length <= 1) {
    return images.map((img) => ({ imageIds: [img.id] }))
  }

  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not configured')
  }

  const { output } = await generateText({
    model: openai('gpt-5'),
    output: Output.object({ schema: imageGroupingSchema }),
    system: `You are a product image analyst for a fashion e-commerce store.
You will receive multiple product images, each labelled with [Image ID: N].
Your task is to group the images so that every image of the SAME product ends up in the same group,
and images of DIFFERENT products are placed in separate groups.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

- Same product: the same garment or item shown from different angles, on a model vs flat lay,
  or with/without styling — front view, back view, detail close-up, hanger shot, lifestyle shot
  of the exact same piece all belong together.
- Different products: distinct designs, silhouettes, or item types belong in separate groups,
  even if the price, brand, or colour appears identical.
- Different colourways of the same base design → put in the SAME group.
  They will be handled as colour variants when the product is created.
- Every image ID must appear in exactly one group — no image may be omitted or duplicated.
- When uncertain whether two images show the same product, prefer splitting into separate groups.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXAMPLES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXAMPLE 1 — Same polo shirt, front and back shot (IDs 10, 11):
  [Image ID: 10] white Lacoste polo shirt, front view on a model
  [Image ID: 11] same white Lacoste polo shirt, back view on the same model
  → groups: [{ imageIds: [10, 11] }]
  ✓ Same polo, different angles — one product.

EXAMPLE 2 — Four different polo shirts, one image each (IDs 20, 21, 22, 23):
  [Image ID: 20] plain black polo shirt on a hanger
  [Image ID: 21] plain white polo shirt on a hanger
  [Image ID: 22] navy polo shirt with a small embroidered logo on a hanger
  [Image ID: 23] burgundy striped polo shirt on a hanger
  → groups: [{ imageIds: [20] }, { imageIds: [21] }, { imageIds: [22] }, { imageIds: [23] }]
  ✓ All polos, but each is a different design — four separate products.
  ✗ Do NOT group them just because they are all polo shirts.

EXAMPLE 3 — Same polo in three colourways (IDs 30, 31, 32):
  [Image ID: 30] slim-fit polo with tipped collar in white
  [Image ID: 31] the same slim-fit polo with tipped collar in navy
  [Image ID: 32] the same slim-fit polo with tipped collar in olive
  → groups: [{ imageIds: [30, 31, 32] }]
  ✓ Identical design, different colours → one group (colour variants).

EXAMPLE 4 — Three different graphic tees, one with a second shot (IDs 40, 41, 42, 43):
  [Image ID: 40] black tee with a large dragon print, front view
  [Image ID: 41] black tee with a large dragon print, back view showing full print detail
  [Image ID: 42] white tee with a small "NYC" chest graphic, front view
  [Image ID: 43] grey tee with a washed vintage Nirvana print, front view
  → groups: [{ imageIds: [40, 41] }, { imageIds: [42] }, { imageIds: [43] }]
  ✓ Dragon tee has two shots → grouped. The other two tees are different designs → separate.

EXAMPLE 5 — Five different joggers, some with multiple shots (IDs 50, 51, 52, 53, 54):
  [Image ID: 50] black slim-fit joggers, front view
  [Image ID: 51] black slim-fit joggers, back view
  [Image ID: 52] grey marl joggers with side stripe, front view
  [Image ID: 53] olive cargo joggers with zip pockets, front view
  [Image ID: 54] olive cargo joggers with zip pockets, close-up of pocket detail
  → groups: [{ imageIds: [50, 51] }, { imageIds: [52] }, { imageIds: [53, 54] }]
  ✓ Each distinct jogger design is its own product; multiple shots of the same piece stay together.

EXAMPLE 6 — Same hoodie design in two colourways, each with a front and back shot (IDs 60, 61, 62, 63):
  [Image ID: 60] oversized grey hoodie, front view
  [Image ID: 61] oversized grey hoodie, back view
  [Image ID: 62] same oversized hoodie design in black, front view
  [Image ID: 63] same oversized hoodie design in black, back view
  → groups: [{ imageIds: [60, 61, 62, 63] }]
  ✓ Same base design across both colourways — one product with colour variants.
  ✗ Do NOT split by colour into two groups; colour is handled as a variant.`,
    messages: [
      {
        role: 'user',
        content: [
          { type: 'text', text: 'Group these product images:' },
          ...images.flatMap((img) => [
            { type: 'text' as const, text: `[Image ID: ${img.id}]` },
            { type: 'image' as const, image: img.url },
          ]),
        ],
      },
    ],
  })

  if (!output) {
    throw new Error('AI did not return image grouping data')
  }

  const groups = output.groups.filter((g) => g.imageIds.length > 0)
  if (groups.length === 0) {
    throw new Error('AI returned no image groups')
  }

  const validImageIds = new Set(images.map((img) => img.id))
  const seenImageIds = new Set<number>()

  for (const group of groups) {
    for (const imageId of group.imageIds) {
      if (!validImageIds.has(imageId)) {
        throw new Error(`AI returned unknown image ID: ${imageId}`)
      }

      if (seenImageIds.has(imageId)) {
        throw new Error(`AI returned duplicate image ID: ${imageId}`)
      }

      seenImageIds.add(imageId)
    }
  }

  const missingImageIds = images
    .map((img) => img.id)
    .filter((imageId) => !seenImageIds.has(imageId))

  if (missingImageIds.length > 0) {
    throw new Error(`AI omitted image IDs: ${missingImageIds.join(', ')}`)
  }

  return groups
}
